version: '3'
networks:
  web:
services:
  mysql:
    image: mysql:5.7
    volumes:
      - C:\data\mysql:/var/lib/mysql
    networks:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: V6PEPhasp8
    ports:
      - 3306:3306

  keycloak:
    image: jboss/keycloak:8.0.2
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: V6PEPhasp8
      KEYCLOAK_USER: adminn
      KEYCLOAK_PASSWORD: Pa55w0rd
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "useSSL=false"
    networks:
      - web
    ports:
      - 8080:8080
    depends_on:
      - mysql


